#redis
spring:
  redis:
    host: 47.96.150.59
    port: 6379
    password: 1314520

#mysql数据库
  datasource:
    # 配置druid数据库连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_middleware?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: 123456
    # 配置前端传输的时间模板格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  check-config-location: true
  mapper-locations: classpath:mappers/*.xml
